<?php if (!defined('OMURGA_INIT')) { http_response_code(403); exit; } ?>
<section class="om-user-center om-user-center-mode-<?=e($mode)?>">
  <style>
    .om-user-center{--om-accent:#f97316;--om-dark:#111827;--om-soft:#f8fafc;--om-line:#e5e7eb;--om-muted:#64748b;--om-green:#16a34a;--om-blue:#2563eb;display:block;width:100%;box-sizing:border-box;color:#0f172a}
    .om-user-center *{box-sizing:border-box}.om-user-shell{display:grid;grid-template-columns:260px minmax(0,1fr);gap:18px;align-items:start}.om-user-panel{border:1px solid var(--om-line);border-radius:20px;background:#fff;box-shadow:0 14px 40px rgba(15,23,42,.06)}
    .om-user-side{position:sticky;top:14px;overflow:hidden}.om-user-side-top{padding:18px;background:linear-gradient(135deg,#111827,#334155);color:#fff}.om-user-avatar{width:56px;height:56px;border-radius:18px;background:rgba(255,255,255,.14);display:flex;align-items:center;justify-content:center;font-size:24px;font-weight:900;margin-bottom:10px}.om-user-side-top h2{margin:0;font-size:19px}.om-user-side-top p{margin:5px 0 0;color:#cbd5e1;font-size:13px}.om-user-tabs{display:grid;gap:6px;padding:10px}.om-user-tabs a{border-radius:13px;padding:11px 12px;text-decoration:none;color:#334155;background:#fff;font-weight:800;font-size:14px;display:flex;align-items:center;gap:8px}.om-user-tabs a.active,.om-user-tabs a:hover{background:#fff7ed;color:#c2410c}.om-user-logout{display:block;margin:0 10px 10px;border:1px solid var(--om-line);border-radius:13px;text-align:center;text-decoration:none;color:#334155;padding:10px;font-weight:800}
    .om-user-main{min-width:0}.om-user-hero{padding:20px;margin-bottom:14px;display:flex;align-items:center;justify-content:space-between;gap:14px;background:linear-gradient(135deg,#fff7ed,#ffffff)}.om-user-hero h1{margin:0;font-size:clamp(24px,3vw,36px)}.om-user-hero p{margin:6px 0 0;color:var(--om-muted)}.om-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:14px}.om-stat{padding:14px;border:1px solid var(--om-line);border-radius:16px;background:#fff}.om-stat b{display:block;font-size:24px}.om-stat span{color:var(--om-muted);font-size:13px;font-weight:700}.om-user-card{border:1px solid var(--om-line);border-radius:20px;background:#fff;padding:18px;margin-bottom:14px;box-shadow:0 10px 30px rgba(15,23,42,.04)}
    .om-user-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.om-user-center label{display:grid;gap:6px;font-weight:800;color:#334155;margin-bottom:12px}.om-user-center input,.om-user-center textarea,.om-user-center select{width:100%;border:1px solid var(--om-line);border-radius:12px;padding:11px 12px;font:inherit;background:#fff}.om-user-center textarea{min-height:220px;resize:vertical}.om-user-center small{color:var(--om-muted);font-weight:600}.om-user-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.om-user-btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;border:1px solid var(--om-line);border-radius:12px;background:#fff;color:#1f2937;text-decoration:none;padding:10px 13px;font-weight:900;cursor:pointer}.om-user-btn.primary{background:var(--om-accent);border-color:var(--om-accent);color:#fff}.om-user-alert{border-radius:14px;padding:12px 14px;margin-bottom:14px;background:#f8fafc;border:1px solid var(--om-line);font-weight:700}.om-user-alert.success{background:#ecfdf5;border-color:#bbf7d0}.om-user-alert.error{background:#fef2f2;border-color:#fecaca}
    .om-user-table{width:100%;border-collapse:collapse}.om-user-table th,.om-user-table td{border-bottom:1px solid var(--om-line);padding:12px 10px;text-align:left;vertical-align:top}.om-user-table small,.om-user-muted{color:var(--om-muted)}.om-status-pill{display:inline-flex;border-radius:999px;padding:6px 10px;background:#f1f5f9;font-weight:900;font-size:12px}.om-status-published{background:#dcfce7;color:#166534}.om-status-pending{background:#fef3c7;color:#92400e}.om-form-section{border:1px solid var(--om-line);border-radius:16px;padding:14px;margin:14px 0;background:#fbfdff}.om-form-section-title{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:10px}.om-form-section-title strong{font-size:17px}.om-form-section-title small{display:block}.om-field-group-title{font-weight:900;margin:12px 0 8px;color:#0f172a}.check-line{display:flex!important;align-items:center;gap:8px}.check-line input{width:auto!important}.om-current-image{max-width:180px;border-radius:12px;border:1px solid var(--om-line);margin-top:8px}
    @media(max-width:860px){.om-user-shell{grid-template-columns:1fr}.om-user-side{position:static}.om-user-tabs{display:flex;overflow:auto}.om-user-tabs a{white-space:nowrap}.om-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.om-user-hero{display:block}.om-user-grid{grid-template-columns:1fr}.om-user-table,.om-user-table tbody,.om-user-table tr,.om-user-table td{display:block;width:100%}.om-user-table thead{display:none}.om-user-table td{padding:8px 0}}
  </style>
  <?php $stats=omurga_user_center_post_stats((int)$user['id']); $initial=mb_strtoupper(mb_substr((string)($user['name'] ?? $user['username'] ?? 'U'),0,1,'UTF-8'),'UTF-8'); ?>
  <div class="om-user-shell">
    <aside class="om-user-panel om-user-side">
      <div class="om-user-side-top"><div class="om-user-avatar"><?=e($initial)?></div><h2><?=e($user['name'] ?? $user['username'] ?? $user['email'] ?? '')?></h2><p><?=e(omurga_role_labels()[$user['role'] ?? 'member'] ?? ($user['role'] ?? 'member'))?></p></div>
      <?php if($mode === 'center'): ?><nav class="om-user-tabs"><?php foreach($tabs as $key=>$label): ?><a class="<?=$tab===$key?'active':''?>" href="<?=e(omurga_user_center_url($key))?>"><?=e($label)?></a><?php endforeach; ?></nav><?php endif; ?>
      <a class="om-user-logout" href="<?=e(omurga_url('admin/logout.php'))?>"><?=e(om_t('blocks.logout','Çıkış'))?></a>
    </aside>
    <main class="om-user-main">
      <div class="om-user-panel om-user-hero"><div><h1><?=e($tab==='submit' ? om_t('user_center.new_post','Yeni Yazı') : om_t('user_center.title','Hesabım'))?></h1><p><?=e(om_t('user_center.reporter_intro','Yazılarını buradan gönder, takip et ve güncelle.'))?></p></div><?php if(omurga_user_center_can_write()): ?><a class="om-user-btn primary" href="<?=e(omurga_user_center_url('submit'))?>">Yeni haber gönder</a><?php endif; ?></div>
      <?php if(omurga_user_center_can_write()): ?><div class="om-stats"><div class="om-stat"><b><?=e((string)$stats['total'])?></b><span>Toplam yazı</span></div><div class="om-stat"><b><?=e((string)$stats['pending'])?></b><span>İncelemede</span></div><div class="om-stat"><b><?=e((string)$stats['published'])?></b><span>Yayınlanan</span></div><div class="om-stat"><b><?=e((string)$stats['draft'])?></b><span>Taslak</span></div></div><?php endif; ?>
      <?php if(!empty($notice['message'])): ?><div class="om-user-alert <?=e($notice['type'] ?? '')?>"><?=e($notice['message'])?></div><?php endif; ?>

      <?php if($tab === 'profile'): ?>
        <form class="om-user-card" method="post"><?=csrf_field()?><input type="hidden" name="user_center_action" value="profile"><div class="om-user-grid"><label><?=e(om_t('user_center.name','Ad Soyad'))?><input name="name" value="<?=e($user['name'] ?? '')?>" required></label><label><?=e(om_t('user_center.email','E-posta'))?><input type="email" name="email" value="<?=e($user['email'] ?? '')?>" required></label></div><div class="om-user-actions"><button class="om-user-btn primary"><?=e(om_t('user_center.save','Kaydet'))?></button></div></form>
      <?php elseif($tab === 'posts'): $rows=omurga_user_center_posts((int)$user['id']); ?>
        <div class="om-user-card"><table class="om-user-table"><thead><tr><th><?=e(om_t('user_center.post_title','Başlık'))?></th><th><?=e(om_t('user_center.status','Durum'))?></th><th></th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="3"><?=e(om_t('user_center.no_posts','Henüz yazınız yok.'))?></td></tr><?php endif; ?><?php foreach($rows as $row): $st=$row['status'] ?? 'draft'; ?><tr><td><strong><?=e($row['title'])?></strong><br><small><?=e($row['created_at'] ?? '')?></small></td><td><span class="om-status-pill om-status-<?=e($st)?>"><?=e(omurga_public_status_label($row))?></span></td><td><a class="om-user-btn" href="<?=e(omurga_user_center_url('submit',['edit'=>(int)$row['id']]))?>"><?=e(om_t('user_center.edit','Düzenle'))?></a></td></tr><?php endforeach; ?></tbody></table></div>
      <?php elseif($tab === 'submit' && omurga_user_center_can_write()): $cats=omurga_user_center_categories(); $typeForFields=(string)($editPost['type'] ?? primary_content_type()); ?>
        <form class="om-user-card" method="post" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="user_center_action" value="post_save"><input type="hidden" name="post_id" value="<?=e((string)($editPost['id'] ?? 0))?>"><input type="hidden" name="MAX_FILE_SIZE" value="12582912">
          <div class="om-form-section"><div class="om-form-section-title"><strong>Haber İçeriği</strong><small>Başlık, spot ve ana metin.</small></div><label><?=e(om_t('user_center.post_title','Başlık'))?><input name="title" value="<?=e($editPost['title'] ?? '')?>" required></label><div class="om-user-grid"><label>Slug<input name="slug" value="<?=e($editPost['slug'] ?? '')?>" placeholder="<?=e(om_t('user_center.slug_auto','Boşsa başlıktan oluşur'))?>"></label><label><?=e(om_t('user_center.excerpt','Kısa açıklama'))?><input name="spot" value="<?=e($editPost['spot'] ?? '')?>"></label></div><label><?=e(om_t('user_center.content','İçerik'))?><textarea name="content" required><?=e($editPost['content'] ?? '')?></textarea></label></div>
          <div class="om-form-section"><div class="om-form-section-title"><strong>Haber Bilgileri</strong><small>Kategori ve medya alanları.</small></div><div class="om-user-grid"><label>Kategori<select name="category_id"><option value="0">Kategori seç</option><?php foreach($cats as $c): ?><option value="<?=e((string)$c['id'])?>" <?=((int)($editPost['category_id'] ?? 0)===(int)$c['id'])?'selected':''?>><?=e($c['name'])?></option><?php endforeach; ?></select></label><label>Video URL<input type="url" name="video_url" value="<?=e($editPost['video_url'] ?? '')?>" placeholder="https://..."></label></div><label>Öne çıkan görsel <input type="file" name="featured_upload" accept="image/*"><input name="featured_image" value="<?=e($editPost['featured_image'] ?? '')?>" placeholder="uploads/ornek.webp"><small>Dosya seçersen otomatik yüklenir; istersen mevcut medya yolunu da yazabilirsin.</small><?php if(!empty($editPost['featured_image'])): ?><img class="om-current-image" src="<?=e(image_url($editPost['featured_image']))?>" alt=""><?php endif; ?></label><label>Galeri görselleri <input type="file" name="gallery_uploads[]" accept="image/*" multiple><textarea name="gallery_images" rows="3" placeholder="Her satıra bir görsel yolu"><?=e($editPost['gallery_images'] ?? '')?></textarea></label></div>
          <?=function_exists('omurga_render_custom_fields_frontend') ? omurga_render_custom_fields_frontend($typeForFields, $editPost ?: ['type'=>$typeForFields,'category_id'=>0]) : ''?>
          <?php if(can('posts.publish')): ?><label><?=e(om_t('user_center.status','Durum'))?><select name="status"><?php foreach(omurga_status_options_for_current_user($editPost['status'] ?? 'draft') as $k=>$v): ?><option value="<?=e($k)?>" <?=($editPost['status'] ?? 'draft')===$k?'selected':''?>><?=e($v)?></option><?php endforeach; ?></select></label><?php endif; ?>
          <div class="om-user-actions"><button class="om-user-btn primary"><?=e(can('posts.publish') ? om_t('user_center.save','Kaydet') : om_t('user_center.submit_review','İncelemeye Gönder'))?></button><a class="om-user-btn" href="<?=e(omurga_user_center_url('posts'))?>">Yazılarıma dön</a></div>
        </form>
      <?php elseif($tab === 'notifications'): $nt=table_name('notifications'); $st=db()->prepare("SELECT * FROM $nt WHERE user_id IS NULL OR user_id=? ORDER BY is_read ASC,id DESC LIMIT 40"); $st->execute([(int)$user['id']]); $notes=$st->fetchAll(); ?>
        <form class="om-user-card" method="post"><?=csrf_field()?><input type="hidden" name="user_center_action" value="notifications_read"><table class="om-user-table"><thead><tr><th></th><th><?=e(om_t('user_center.notifications','Bildirimler'))?></th><th><?=e(om_t('user_center.date','Tarih'))?></th></tr></thead><tbody><?php if(!$notes): ?><tr><td colspan="3"><?=e(om_t('user_center.no_notifications','Bildirim yok.'))?></td></tr><?php endif; ?><?php foreach($notes as $n): ?><tr><td><input type="checkbox" name="ids[]" value="<?=e((string)$n['id'])?>" <?=empty($n['is_read'])?'':'disabled'?>></td><td><strong><?=e($n['title'])?></strong><br><span class="om-user-muted"><?=e($n['message'] ?? '')?></span></td><td><?=e($n['created_at'] ?? '')?></td></tr><?php endforeach; ?></tbody></table><div class="om-user-actions"><button class="om-user-btn"><?=e(om_t('user_center.mark_read','Okundu yap'))?></button></div></form>
      <?php elseif($tab === 'settings'): ?>
        <form class="om-user-card" method="post"><?=csrf_field()?><input type="hidden" name="user_center_action" value="password"><div class="om-user-grid"><label><?=e(om_t('user_center.password','Yeni şifre'))?><input type="password" name="password" required></label><label><?=e(om_t('user_center.password_repeat','Şifre tekrar'))?><input type="password" name="password2" required></label></div><div class="om-user-actions"><button class="om-user-btn primary"><?=e(om_t('user_center.password_save','Şifreyi Güncelle'))?></button></div></form>
      <?php endif; ?>
    </main>
  </div>
</section>
